### ISSUE TITLE
Education to Work is Not Linked

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#884] opened 2023-05-01 22:27 UTC
This is an Equity Council use case.

This issue replaces #873 

Need to support functionality to indicate a Credential, Learning Opportunity, Learning Program, Course or Assessment Profile isPrepartionFor, isRequiredFor, isRecommenedFor a Job, Occupation or Work Role and very likley also a Task.

Add: ceterms:targetJob - Job that is a focus of the resource.
Add: ceterms:targetOccupation - Occupation that is a focus of the resource. 
Add: ceterms:targetTask - Task that is a focus of the resource.

URI: ceterms:targetJob
Label: Target Job
Definition: Job that is the focus of a resource.
Domain: cetermsceterms:ConditionProfile
Range: ceterms:Job

That would enable a path like
Credential > isRequiredFor > ConditionProfile > targetJob > Job

URI: ceterms:targetOccupation
Label: Target Occupation
Definition: Occupation that is the focus of a resource.
Domain: ceterms:ConditionProfile
Range: ceterms:Occupation

URI: ceterms:targetTask
Label: Target Task
Definition:Task that is the focus of a resource.
Domain: ceterms:ConditionProfile
Range: ceterms:Job

Domain Includes: ceterms:ConditionProfile, ceterms:Credential, ceterms:LearningOpportunity, ceterms: Course, ceterms:AsssesmentProfile

**Comment by siuc-nate** [comment] 2023-05-02 14:07
Is this a duplicate of #873 ?

**Comment by siuc-nate** [comment] 2023-05-08 16:12
Routing it through Condition Profile is intentional, as it allows us all of the contextualization there that we gain by going through it in other use cases.

The definitions were (loosely) based on the existing definitions for the various "target____" properties.  They could probably all do with some cleanup/examination.

**Comment by siuc-nate** [comment] 2023-05-08 16:23
Per our 2023-05-08 meeting:
There is preference for the idea of a "target occupation" rather than a "target job", as the former is more practical than the latter in terms of "I am publishing a credential, it is for ____".

**Comment by siuc-nate** [comment] 2023-05-09 14:51
Proposal:

**Create rdf:Property - ceterms:targetOccupation**
> **Status:** vs:unstable
> **Label:** "Target Occupation"
> **Definition:** "Occupationthat is the focus of this resource"
> **Domain:** ceterms:ConditionProfile
> **Range:** ceterms:Occupation


**Create rdf:Property - ceterms:targetJob**
> **Status:** vs:unstable
> **Label:** "Target Job"
> **Definition:** "Job that is the focus of this resource"
> **Domain:** ceterms:ConditionProfile
> **Range:** ceterms:Job

**Comment by siuc-nate** [comment] 2023-05-10 18:15
```
res:O :requires [ :targetOccupation res:O ]   #?! I mean, it's not wrong but it's odd.
```

The Occupation wouldn't require itself. Wouldn't this be:

```
res:O :requires [ :targetCredential res:Cr ] 
```
Though I doubt such a thing could be inferenced without some more complex processing.

Is there some equivalent to owl:inverseOf that allows for the kind of reification/indirection involved in having something between two objects that describes the relationship between them in greater detail? It seems like a limitation of RDF. We'd have the same issue with, for example, the Action classes:
```
(x)-[accredits]->(y)
```
vs
```
(x)-[credentialingAction]->(AccreditActionThatDescribesThingsAndAlsoPointsToOtherStuff)-[object]->(y)
```

**Comment by philbarker** [comment] 2023-05-10 18:39
> > res:O :requires [ :targetOccupation res:O ]   #?! I mean, it's not wrong but it's odd.
>
> The Occupation wouldn't require itself. 

You would have
```
res:O :requires  res:CP .

res:CP  :targetOccupation res:O . # was given earlier

# hence

res:O :requires [   :targetOccupation res:O  ]  .
```

> Wouldn't this be:
> 
> > res:O :requires [ :targetCredential res:Cr ]

Nothing implies being able to turn `res:Cr :isRequiredFor res:CP .` into `res:O :requires [ :targetCredential res:Cr ]`

> Is there some equivalent to owl:inverseOf that allows for the kind of reification/indirection involved in having something between two objects that describes the relationship between them in greater detail? It seems like a limitation of RDF. We'd have the same issue with, for example, the Action classes

It's a limitation of the model built on RDF, not of RDF.  Don't use the same property to point to things that behave differently, then it works.

Given different properties for a strict requirement and a contextualized requirement and given a definition of "targetX" that allows an inverse this can be modelled in RDF.

**Comment by siuc-nate** [comment] 2023-05-10 21:22
A lot of that is what I was getting at with:
>Though I doubt such a thing could be inferenced without some more complex processing.

>Given different properties for a strict requirement and a contextualized requirement and given a definition of "targetX" that allows an inverse this can be modelled in RDF.

What would an example of this be? Would you need separate properties for every possible combination of "thing that points to condition profile" + "thing that a condition profile references"?  We should keep in mind that a condition profile could constrain an isRequiredFor relationship to just certain jurisdictions, audiences, or different combinations of 2-n target____s and so on.

**Comment by siuc-nate** [comment] 2023-05-10 21:24
Also, current discussion aside, we are ready to implement the changes from [this post](https://github.com/CredentialEngine/Schema-Development/issues/884#issuecomment-1540286763), correct?

**Comment by philbarker** [comment] 2023-05-11 08:56
@siuc-nate Sorry I don't have time to go much deeper into this rabbit hole unless there is a real prospect of changing how requirements are handled (that would be a breaking change). 

The current proposal just continues with something that is already problematic (having requires point to something directly and point to a more complex set of conditions). As I have said twice above: with caveats, I'm happy with this proposal.

**Comment by siuc-nate** [comment] 2023-05-12 19:07
The changes from [this post](https://github.com/CredentialEngine/Schema-Development/issues/884#issuecomment-1540286763) have been made in pending CTDL and noted in the history tracking.

I recommend we close this issue and, if needed, continue the discussion in a separate one.

**Closed by siuc-nate** 2023-05-12 19:07 UTC
Labels: Schema, High Priority
