### ISSUE TITLE
Add Support Services Description and Support Services Webpage to Credential Organizations

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#902] opened 2023-09-22 18:06 UTC
Add Support Services Description and Support Services Web Page to Credential Organizations

Support Services Description is for text.
Support Services Webpage.

**Comment by siuc-nate** [comment] 2023-09-25 15:09
Isn't this already accommodated by the Support Service class itself? It has description and subjectWebpage properties, and can be used in a high-level/summary sense (like those pair-properties on organization).

**Comment by siuc-nate** [comment] 2023-09-25 16:24
Do these work? based on https://credreg.net/ctdl/terms/transferValueStatement and https://credreg.net/ctdl/terms/transferValueStatementDescription):

> **URI:** ceterms:supportServiceStatement
> **Label:** Support Service Statement
> **Definition:** Webpage or online document that defines or explains the nature of support services offered by the organization.
> **Domain:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
> **Range:** xsd:anyURI

> **URI:** ceterms:supportServiceDescription
> **Label:** Support Service Description
> **Definition:** Description of the nature of support services by the organization.
> **Domain:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
> **Range:** rdf:langString

**Comment by philbarker** [comment] 2023-09-26 13:01
I'll keep saying that `Range: xsd:anyURI` is poor RDF. In this case `Range: schema:WebPage` would be better. And @siuc-nate will keep ignoring me.

**Comment by philbarker** [comment] 2023-09-26 13:01
But other than that this is OK

**Comment by siuc-nate** [comment] 2023-09-26 15:53
I'm not ignoring you, Phil - I don't recall seeing schema:WebPage before. Is that a new suggestion? I know we've talked about things like rdfs:Resource in the past.

**Comment by philbarker** [comment] 2023-09-26 16:06
No offence meant or implied Nate; just an off the cuff remark. Sorry, it does read different to how it was intended.
 
Yes it is a new take on this. rdfs:Resource will always be valid so it works as a general global replacement, but I think that much of the time we use xsd:anyURI for pointing to web pages, as in this case, so schema:WebPage would a good replacement here.

**Comment by siuc-nate** [comment] 2023-09-26 16:11
No worries, I thought that might've been the case.

And, that's interesting.  We should probably consider that as a range in other cases too, across the schema.  That would probably need to be its own issue (or merged into the rdfs:Resource one).

**Comment by siuc-nate** [comment] 2023-09-27 17:21
These changes (including the use of schema:WebPage) have been made in pending CTDL and noted in the history tracking.

**Closed by siuc-nate** 2023-09-27 17:21 UTC
Labels: Support Services
