### ISSUE TITLE
Reconsider ceasn:competencyCategory's rdf:langString range

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#657] opened 2020-03-11 14:45 UTC
Some time ago, Jim Goodell asked me whether CTDL-ASN had a companion property to [ceasn:competencyCategory](https://purl.org/ctdlasn/terms/competencyCategory) for references to categories defined in concept schemes. I have been pondering whether creation of another property with a range of [ceterms:CredentialAlignmentObject](https://purl.org/ctdl/terms/CredentialAlignmentObject) was necessary or whether we should not simply change the range of [ceasn:competencyCategory](https://purl.org/ctdlasn/terms/competencyCategory) to [ceterms:CredentialAlignmentObject](https://purl.org/ctdl/terms/CredentialAlignmentObject) that could be used to handle either case; i.e., using [ceterms:targetNode](https://purl.org/ctdl/terms/targetNode) (and perhaps even [ceterms:targetNodeName](https://purl.org/ctdl/terms/targetNodeName)) for referencing a category in a concept scheme AND just [ceterms:targetNodeName](https://purl.org/ctdl/terms/targetNodeName) when all that was present was a literal? Since the underlying assumption is that either way, the values are from some controlled value space (formally declared or not), the fit with [CredentialAlignmentObject](https://purl.org/ctdl/terms/CredentialAlignmentObject) is appropriate. 

The reason that is defined solely as an `rdf:langString` is purely historical. When the property was defined in ASN nearly 20 years ago, controlled value spaces weren't as prevalent...and, we just didn't see how usage would evolve. 

I understand the namespace policy and technical issues of changing the range, but hearing from others on the approach would be appreciated. *It is not a new conversation.* We've discussed the use of bnodes for handling literals in contexts where the value might also be a a reference to a concept resource. This method has been deployed in other principled contexts.

(+ bloody wish we could use [schema:DefinedTerm](https://schema.org/DefinedTerm) instead of [ceterms:CredentialAlignmentObject](https://purl.org/ctdl/terms/CredentialAlignmentObject)...)

**Comment by siuc-nate** [comment] 2020-03-11 15:19
While I don't know off the top of my head what the technical implications would be for a change like that (they would affect data in CASS quite a bit, for sure), I think a more future-proof approach would be to use `skos:Concept` rather than `ceterms:CredentialAlignmentObject`, since that would allow us to:

1. Reference Concepts where they already exist, and
2. Use embedded bnodes with a `@type` of `skos:Concept` where they do not

That way we aren't using Credential Alignment Objects as pseudo-Concept nodes.

That said, it might be worth considering whether or not this would be better done with a new property.  I'm not sure there.

**Comment by Lomilar** [comment] 2020-03-11 15:29
skos:Concepts rigidly (ala 2 object model) identify the scheme they come from, so I'm not seeing the need for alignment object. Is there a need for a verb?

Having a range of schema:URL or schema:Text isn't too much of an ask either.

I'm not sure if we need alignmentObject, unless we need to further annotate the connection with additional information.

**Comment by siuc-nate** [comment] 2021-03-01 16:42
Closing this as a duplicate of #626

**Closed by siuc-nate** 2021-03-01 16:42 UTC
Labels: CTDL-ASN
